#!/usr/bin/env bash
# Bash script that transfers a file from client to a server

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

path_to_file=$1
server_ip=$2
scp_username=$3
path_to_sshkey=$4

scp -o StrictHostKeyChecking=no -i "$path_to_sshkey" "$path_to_file" "$scp_username@$server_ip":~/
