#!/usr/bin/env bash
# Bash script that configures a new ubuntu machine as a web server

# update package list
apt-get update

# install nginx
apt-get install -y nginx

ufw allow 'Nginx HTTP'

echo "Hello World!" > /var/www/html/index.html

service nginx start
