#!/usr/bin/env bash
# Bash script that configures apache server and 301 page

# update
sudo apt-get update

# install nginx
sudo apt-get install -y nginx

# setup index page and 301 redirect
echo "Hello World!" | sudo tee /var/www/html/index.html
replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.ghbizdirectory.com permanent;"
sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default

# setup 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
replacement_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
