#!/usr/bin/env bash
# A Bash script that setup a new server to meet rquirement

# update
sudo apt-get update
# install nginx
sudo apt-get -y install nginx

# firewall allow port 80
sudo ufw allow 'Nginx HTTP'

# create html directory
sudo mkdir -p /var/www/html

# change permissions
sudo chmod -R 755 /var/www

#  create the index page
echo 'Hello World!' | sudo tee  /var/www/html/index.html

# create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# setup redirect
replacement_string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.ghbizdirectory.com permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# configure redirect for 404 error page
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

# restart nginx
sudo service nginx restart
