#!/usr/bin/env bash
# A script install and setup load balancer

sudo apt-get update

sudo apt-get -y install haproxy

# configuration
server_config=\
"
frontend  dannyose-frontend
        bind *:80
        mode http
        default_backend dannyose-backend
backend dannyose-backend
        balance roundrobin
        server 238856-web-01 18.204.5.48:80 check
        server 238856-web-02 34.229.184.150:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# allow haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
