#!/usr/bin/env bash
#  A Bash script that displays numbers from 1 to 100.
#+ Displays FizzBuzz when the number is a multiple of 3 and 5
#+ Displays Fizz when the number is multiple of 3
#+ Displays Buzz when the number is a multiple of 5
#+ Otherwise, displays the number
#+ In a list format

# Loop through numbers from 1 to 100 using a for loop
for number in {1..100}; do
    # Check if the number is a multiple of both 3 and 5
    if ((number % 3 == 0)) && ((number % 5 == 0)); then
	echo "FizzBuzz"
	# Check if the number is a multiple of 3
    elif ((number % 3 == 0)); then
	echo "Fizz"
	# Check if the number is a multiple of 5
    elif ((number % 5 == 0)); then
	echo "Buzz"
	# Otherwise, print the number
    else
	echo "$number"
    fi
done
								    
