#!/usr/bin/env bash
#  Write a Bash script that displays:
#+ The content of the current directory
#+ In a list format
#+ Where only the part of the name after the first dash is displayed

files=$(ls)
for file in $files; do
    filename=$(echo "$file" | cut -d '-' -f 2-)

    echo "$filename"
done
