#!/usr/bin/env bash
# script to configure firewall
# enable port 22, 443, 80 /tcp
sudo apt update
sudo apt-get install ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

