#!/usr/bin/env bash

# Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu

server="34.205.65.3"
private_key="~/.ssh/school"
user="ubuntu"

ssh -i $private_key $user@$server
