#!/usr/bin/env bash

# Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu

server="34.205.65.3"
user="ubuntu"

ssh -i "$HOME/.ssh/school" "$user"@"$server"
